# 8. MNIST 손글씨 이미지 분류하기

<img src="https://codetorial.net/tensorflow/_images/MNIST_sample.png"/>

MNIST 데이터셋은 위 그림과 같이 0에서 9까지 10가지로 분류될 수 있는 손글씨 숫자 이미지 70,000개로 이루어져 있습니다.

각 이미지는 28*28 픽셀로 구성되고, 각 픽셀은 아래와 같이 0~255 사이의 숫자 행렬로 표현됩니다.

In [ ]:
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
[  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
[  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
[  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 182 247 241   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0  80 156 107 253 253 205  11   0  43 154   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0  14   1 154 253  90   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0 139 253 190   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0  11 190 253  70   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0  35 241 225 160 108   1   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0  81 240 253 253 119  25   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0  45 186 253 253 150  27   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0  16  93 252 253 187   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 249 253 249  64   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0  46 130 183 253 253 207   2   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0  39 148 229 253 253 253 250 182   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0  24 114 221 253 253 253 253 201  78   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0  23  66 213 253 253 253 253 198  81   2   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0  18 171 219 253 253 253 253 195  80   9   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0  55 172 226 253 253 253 253 244 133  11   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0 136 253 253 253 212 135 132  16   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]

## Table of Contents

1. 훈련 데이터 준비하기
2. 뉴런층 만들기
3. Neural Network 구성하기
4. Neural Network 컴파일하기
5. 은닉층의 출력값 확인하기
6. 출력층의 출력값 확인하기 

## 예제

In [ ]:
import tensorflow as tf

#1. MNIST 데이터셋 임포트
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

#2. 데이터 전처리
x_train, x_test = x_train/255.0, x_test/255.0

#3. 모델 구성

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(512, activation=tf.nn.relu),
    tf.keras.layers.Dense(20,activation=tf.nn.softmax)
])

# 4. 모델 컴파일
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

#5. 모델 훈련
model.fit(x_train, y_train, epochs=5)

#6. 정확도 평가
test_loss, test_acc = model.evaluate(x_test, y_test)
print('테스트 Loss : ', test_loss)
print('테스트 정확도 : ', test_acc)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2090 - accuracy: 0.9391
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0823 - accuracy: 0.9747
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0527 - accuracy: 0.9834
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0371 - accuracy: 0.9880
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.0784 - accuracy: 0.9781
테스트 Loss :  0.07842844724655151
테스트 정확도 :  0.9781000018119812


## 1) 훈련 데이터 준비하기

In [ ]:
import tensorflow as tf 
import numpy as np

tf.random.set_seed(0)

# 1. 훈련 데이터 준비하기
x_train = np.array([[1,0,0], [0,1,0], [0,0,1]])
y_train = np.array([[0],[1],[1]])

우선 tf.random 모듈의 set_seed()함수를 사용해서 랜덤 시드를 설정했습니다.

예제에서 x_train, y_train은 각각 훈련에 사용할 입력값, 출력값입니다.

이 페이지에서는 훈련은 진행하지 않고 입력 데이터(x_train)에 대해 각 뉴런층이 출력하는 값을 확인합니다.

## 2) 뉴런층 만들기 

In [ ]:
# 2. 뉴런층 만들기
input_layer = tf.keras.layers.InputLayer(input_shape = (3,))
hidden_layer = tf.keras.layers.Dense(units=4, activation = 'relu')
output_layer = tf.keras.layers.Dense(units=2, activation = 'softmax')

아래와 같은 간단한 신경망 모델을 구성하기 위한 뉴런층을 각각 만들었습니다.

길이 3을 갖는 벡터 입력을 받고, 은닉층은 네 개의 뉴런 노드를 가지며, 출력층은 두 개의 뉴런 노드를 가집니다.

은닉층의 활성화함수는 'relu', 출력층의 활성화함수는 'softmax'로 지정했습니다.

<img src="https://codetorial.net/tensorflow/_images/get_output_of_neuron_layers_1.png"/>

## 3) Neural Network 구성하기

In [ ]:
# 3. 모델 구성하기

model = tf.keras.Sequential([
    input_layer,
    hidden_layer,
    output_layer
])

tf.keras 모듈의 Sequential 클래스는 Neural Network의 각 층을 순서대로 쌓을 수 있도록 합니다.

앞에서 만든 뉴런층을 순서대로 입력해서 신경망 모델을 구성합니다.

## 4) Neural Network 컴파일하기



In [ ]:
# 4. 모델 컴파일하기
model.compile(loss = 'mse', optimizer = 'Adam')

손실 함수로 'mse'를, 옵티마이저로 'Adam'을 지정했습니다.

이 페이지의 예제에서는 훈련을 진행하지 않기 때문에 컴파일 과정은 생략할 수 있습니다.

## 5) 은닉층의 출력값 확인하기

In [ ]:
# 5. 은닉층의 출력 확인하기

intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(x_train)

print('=========== Inputs ============')
print(x_train)

print()
print('=========== Weights of Hidden Layer ==============')
print(hidden_layer.get_weights()[0])

print()
print('=========== Outputs of Hidden Layer ==============')
print(intermediate_output)

tf.keras 모듈의 Model 클래스를 사용해서 새로운 모델(intermediate_layer_model)을 하나 만들었습니다.

이 모델은 앞에서 구성한 전체 모델의 입력을 입력으로 하고,

첫 번째 뉴런층(hidden_layer)의 출력을 출력으로 하는 신경망 모델입니다.

이 모델에 훈련 데이터(x_train)을 입력하면 첫 번째 뉴런층의 출력을 반환합니다.

<img src="https://codetorial.net/tensorflow/_images/get_output_of_neuron_layers_2.png"/>

첫 번째 뉴런층, 즉 은닉층의 출력은 아래와 같이 계산됩니다.

<img src="https://codetorial.net/tensorflow/_images/get_output_of_neuron_layers_3.png"/>

## 6) 출력층의 출력값 확인하기

출력층의 출력값은 전체 Neural Network 신경망의 출력값입니다.

In [ ]:
# 6. 출력층의 출력 확인하기 
pred = model.predict(x_train)

print()
print("=============== Outputs of Output Layer================")
print(pred)

전체 신경망의 출력값은 Model 클래스의 predict() 메서드를 사용해서 간단하게 얻을 수 있습니다.

세 개의 값을 갖는 세 개의 입력 데이터 벡터에 대해 두 개의 값을 갖는 벡터 세 개를 출력합니다.



## 전체 예제 코드

전체 코드는 아래와 같습니다.

In [ ]:
import tensorflow as tf
import numpy as np

tf.random.set_seed(0)


# 1. 훈련 데이터 준비하기
x_train = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
y_train = np.array([[0], [1], [1]])


# 2. 뉴런층 만들기
input_layer = tf.keras.layers.InputLayer(input_shape=(3,))
hidden_layer = tf.keras.layers.Dense(units=4, activation='relu')
output_layer = tf.keras.layers.Dense(units=2, activation='softmax')


# 3. 모델 구성하기
model = tf.keras.Sequential([
  input_layer,
  hidden_layer,
  output_layer
  ])

# 4. 모델 컴파일하기
model.compile(loss='mse', optimizer='Adam')


# 5. 은닉층의 출력 확인하기
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(x_train)

print('======== Inputs ========')
print(x_train)

print('\n======== Weights of Hidden Layer ========')
print(hidden_layer.get_weights()[0])

print('\n======== Outputs of Hidden Layer ========')
print(intermediate_output)

# 6. 출력층의 출력 확인하기
pred = model.predict(x_train)

print('\n======== Outputs of Output Layer ========')
print(pred)  